---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _specification-v1
  label: Specification v1
  create: all
  match: "**/*"
- type: directory
  path: _emails
  label: Emails
  create: all
  match: "**/*"
- type: directory
  path: _principles
  label: Principles
  create: all
  match: "**/*"
- type: directory
  path: _tutorials
  label: Tutorials
  create: all
  match: "**/*"
- type: directory
  path: _services
  label: Services
  create: all
  match: "**/*"
- type: directory
  path: _components
  label: Components
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle config set path 'vendor/bundle' && bundle install
  preview_docker_image: jekyll/jekyll
  mount_path: _site
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
